# Generated by Django 3.0.5 on 2021-09-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('aadhar', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('documents', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
    ]
