# Generated by Django 3.0.5 on 2021-09-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='documents',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='passport',
            field=models.FileField(upload_to=''),
        ),
    ]
