# Generated by Django 3.0.5 on 2021-09-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210918_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='documents',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='passport',
            field=models.CharField(max_length=20),
        ),
    ]
