# Generated by Django 3.0.5 on 2021-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210918_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='submitted',
            field=models.CharField(default='yes', max_length=255),
            preserve_default=False,
        ),
    ]
