# Generated by Django 3.0.5 on 2021-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_contact_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='submitted',
            field=models.CharField(max_length=25),
        ),
    ]
