# Generated by Django 3.0.5 on 2021-09-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210918_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='submitted',
        ),
        migrations.AddField(
            model_name='contact',
            name='submited',
            field=models.CharField(default='q', max_length=25),
            preserve_default=False,
        ),
    ]
