# Generated by Django 3.0.5 on 2021-09-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210918_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='submited',
        ),
        migrations.AddField(
            model_name='contact',
            name='submitted',
            field=models.CharField(default='no', max_length=25),
            preserve_default=False,
        ),
    ]
