# Generated by Django 3.0.5 on 2021-09-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210918_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
