# Generated by Django 3.0.5 on 2021-09-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='passport',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
