# Generated by Django 3.0.5 on 2021-09-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210918_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='passport',
            field=models.ImageField(default='', upload_to='student/images'),
        ),
    ]
