# Generated by Django 3.0.5 on 2021-09-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210918_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='documents',
            field=models.FileField(default='', upload_to='student/pdf'),
        ),
    ]
