# Generated by Django 3.0.5 on 2021-09-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20210918_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Application',
        ),
    ]
