# Generated by Django 3.0.5 on 2021-09-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20210918_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='passport',
            new_name='photo',
        ),
    ]
