# Generated by Django 3.0.5 on 2021-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210918_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pwd',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
